export const annotateTargetList = {
  bioproject: "BioProject",
  biosample: "BioSample",
  chebi: "ChEBI",
  chembl_compound: "ChemblCompound",
  chembl_target: "ChemblTarget",
  clinvar: "ClinVar",
  dbsnp: "DbSNP",
  undefined: "Glycan",
  go: "GO",
  hgnc: "HGNC",
  homologene: "HomoloGene",
  hp: "HP",
  medgen: "MedGen",
  mesh: "MeSH",
  mondo: "Mondo",
  nando: "Nando",
  ncbigene: "NCBIGene",
  pdb: "PDB",
  pubmed: "Pubmed",
  rhea: "Rhea",
  taxonomy: "Taxonomy",
  togovar: "TogoVar",
  uniprot: "UniProt",
  uniprot_mnemonic: "UniProtMnemonic",
};
